// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: character.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const createCharacter = `-- name: CreateCharacter :one
insert into character (owner, name, nationality, age, body, breast, butt, eyes_color, hair_style, hair_color, meta_params) values
    ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) returning id
`

type CreateCharacterParams struct {
	Owner       uuid.UUID
	Name        string
	Nationality string
	Age         int32
	Body        string
	Breast      string
	Butt        string
	EyesColor   string
	HairStyle   string
	HairColor   string
	MetaParams  string
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createCharacter,
		arg.Owner,
		arg.Name,
		arg.Nationality,
		arg.Age,
		arg.Body,
		arg.Breast,
		arg.Butt,
		arg.EyesColor,
		arg.HairStyle,
		arg.HairColor,
		arg.MetaParams,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteCharacter = `-- name: DeleteCharacter :exec
update character set deleted = true where id = $1 and not deleted
`

func (q *Queries) DeleteCharacter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCharacter, id)
	return err
}

const getCharacter = `-- name: GetCharacter :one
select id, created_at, owner, deleted, name, nationality, age, body, breast, butt, eyes_color, hair_style, hair_color, meta_params from character where id = $1 and not deleted limit 1
`

func (q *Queries) GetCharacter(ctx context.Context, id uuid.UUID) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Owner,
		&i.Deleted,
		&i.Name,
		&i.Nationality,
		&i.Age,
		&i.Body,
		&i.Breast,
		&i.Butt,
		&i.EyesColor,
		&i.HairStyle,
		&i.HairColor,
		&i.MetaParams,
	)
	return i, err
}

const listUserCharacters = `-- name: ListUserCharacters :many
select id, created_at, owner, deleted, name, nationality, age, body, breast, butt, eyes_color, hair_style, hair_color, meta_params from character where owner = $1 and not deleted
`

func (q *Queries) ListUserCharacters(ctx context.Context, owner uuid.UUID) ([]Character, error) {
	rows, err := q.db.Query(ctx, listUserCharacters, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Owner,
			&i.Deleted,
			&i.Name,
			&i.Nationality,
			&i.Age,
			&i.Body,
			&i.Breast,
			&i.Butt,
			&i.EyesColor,
			&i.HairStyle,
			&i.HairColor,
			&i.MetaParams,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
