// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: character.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const createCharacter = `-- name: CreateCharacter :one
insert into character (owner_id, name,biography, nationality, age, body, breast, butt, eyes_color, hair_style, hair_color, meta_params) values
    ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) returning id
`

type CreateCharacterParams struct {
	OwnerID     uuid.UUID
	Name        string
	Biography   *string
	Nationality string
	Age         int32
	Body        string
	Breast      string
	Butt        string
	EyesColor   string
	HairStyle   string
	HairColor   string
	MetaParams  string
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createCharacter,
		arg.OwnerID,
		arg.Name,
		arg.Biography,
		arg.Nationality,
		arg.Age,
		arg.Body,
		arg.Breast,
		arg.Butt,
		arg.EyesColor,
		arg.HairStyle,
		arg.HairColor,
		arg.MetaParams,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteCharacter = `-- name: DeleteCharacter :exec
update character set deleted = true where owner_id = $1 and id = $2 and not deleted
`

type DeleteCharacterParams struct {
	OwnerID uuid.UUID
	ID      uuid.UUID
}

func (q *Queries) DeleteCharacter(ctx context.Context, arg DeleteCharacterParams) error {
	_, err := q.db.Exec(ctx, deleteCharacter, arg.OwnerID, arg.ID)
	return err
}

const getPublicCharacter = `-- name: GetPublicCharacter :one
select id, created_at, owner_id, deleted, public, name, biography, nationality, age, body, breast, butt, eyes_color, hair_style, hair_color, meta_params, main_image_id from character where id = $1 and not deleted and public limit 1
`

func (q *Queries) GetPublicCharacter(ctx context.Context, id uuid.UUID) (Character, error) {
	row := q.db.QueryRow(ctx, getPublicCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.OwnerID,
		&i.Deleted,
		&i.Public,
		&i.Name,
		&i.Biography,
		&i.Nationality,
		&i.Age,
		&i.Body,
		&i.Breast,
		&i.Butt,
		&i.EyesColor,
		&i.HairStyle,
		&i.HairColor,
		&i.MetaParams,
		&i.MainImageID,
	)
	return i, err
}

const getUserCharacter = `-- name: GetUserCharacter :one
select id, created_at, owner_id, deleted, public, name, biography, nationality, age, body, breast, butt, eyes_color, hair_style, hair_color, meta_params, main_image_id from character where owner_id = $1 and id = $2 and not deleted limit 1
`

type GetUserCharacterParams struct {
	OwnerID uuid.UUID
	ID      uuid.UUID
}

func (q *Queries) GetUserCharacter(ctx context.Context, arg GetUserCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, getUserCharacter, arg.OwnerID, arg.ID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.OwnerID,
		&i.Deleted,
		&i.Public,
		&i.Name,
		&i.Biography,
		&i.Nationality,
		&i.Age,
		&i.Body,
		&i.Breast,
		&i.Butt,
		&i.EyesColor,
		&i.HairStyle,
		&i.HairColor,
		&i.MetaParams,
		&i.MainImageID,
	)
	return i, err
}

const listPublicCharacters = `-- name: ListPublicCharacters :many
select id, created_at, owner_id, deleted, public, name, biography, nationality, age, body, breast, butt, eyes_color, hair_style, hair_color, meta_params, main_image_id from character where public and not deleted limit $1 offset $2
`

type ListPublicCharactersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPublicCharacters(ctx context.Context, arg ListPublicCharactersParams) ([]Character, error) {
	rows, err := q.db.Query(ctx, listPublicCharacters, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.OwnerID,
			&i.Deleted,
			&i.Public,
			&i.Name,
			&i.Biography,
			&i.Nationality,
			&i.Age,
			&i.Body,
			&i.Breast,
			&i.Butt,
			&i.EyesColor,
			&i.HairStyle,
			&i.HairColor,
			&i.MetaParams,
			&i.MainImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCharacters = `-- name: ListUserCharacters :many
select id, created_at, owner_id, deleted, public, name, biography, nationality, age, body, breast, butt, eyes_color, hair_style, hair_color, meta_params, main_image_id from character where owner_id = $1 and not deleted
`

func (q *Queries) ListUserCharacters(ctx context.Context, ownerID uuid.UUID) ([]Character, error) {
	rows, err := q.db.Query(ctx, listUserCharacters, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.OwnerID,
			&i.Deleted,
			&i.Public,
			&i.Name,
			&i.Biography,
			&i.Nationality,
			&i.Age,
			&i.Body,
			&i.Breast,
			&i.Butt,
			&i.EyesColor,
			&i.HairStyle,
			&i.HairColor,
			&i.MetaParams,
			&i.MainImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
