// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: glossary.sql

package query

import (
	"context"
)

const listGlossaryByType = `-- name: ListGlossaryByType :many
select id, type, value from glossary where type = $1
`

func (q *Queries) ListGlossaryByType(ctx context.Context, type_ string) ([]Glossary, error) {
	rows, err := q.db.Query(ctx, listGlossaryByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Glossary
	for rows.Next() {
		var i Glossary
		if err := rows.Scan(&i.ID, &i.Type, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlossaryByTypeLocal = `-- name: ListGlossaryByTypeLocal :many
select glossary.type, glossary.value, gl.name from glossary join public.glossary_localization gl on glossary.id = gl.glossary_id where glossary.type = $1 and gl.local = $2
`

type ListGlossaryByTypeLocalParams struct {
	Type  string
	Local string
}

type ListGlossaryByTypeLocalRow struct {
	Type  string
	Value string
	Name  string
}

func (q *Queries) ListGlossaryByTypeLocal(ctx context.Context, arg ListGlossaryByTypeLocalParams) ([]ListGlossaryByTypeLocalRow, error) {
	rows, err := q.db.Query(ctx, listGlossaryByTypeLocal, arg.Type, arg.Local)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGlossaryByTypeLocalRow
	for rows.Next() {
		var i ListGlossaryByTypeLocalRow
		if err := rows.Scan(&i.Type, &i.Value, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
