// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const createImage = `-- name: CreateImage :one
insert into character_image (character_id, file_hash) values ($1, $2) returning id
`

type CreateImageParams struct {
	CharacterID uuid.UUID
	FileHash    string
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createImage, arg.CharacterID, arg.FileHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getImage = `-- name: GetImage :one
select id, created_at, character_id, file_hash, is_main from character_image where id = $1 limit 1
`

func (q *Queries) GetImage(ctx context.Context, id uuid.UUID) (CharacterImage, error) {
	row := q.db.QueryRow(ctx, getImage, id)
	var i CharacterImage
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CharacterID,
		&i.FileHash,
		&i.IsMain,
	)
	return i, err
}

const getMainImage = `-- name: GetMainImage :one
select id, created_at, character_id, file_hash, is_main from character_image where character_id = $1 and is_main = true limit 1
`

func (q *Queries) GetMainImage(ctx context.Context, characterID uuid.UUID) (CharacterImage, error) {
	row := q.db.QueryRow(ctx, getMainImage, characterID)
	var i CharacterImage
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CharacterID,
		&i.FileHash,
		&i.IsMain,
	)
	return i, err
}

const listImages = `-- name: ListImages :many
select id, created_at, character_id, file_hash, is_main from character_image where character_id = $1
`

func (q *Queries) ListImages(ctx context.Context, characterID uuid.UUID) ([]CharacterImage, error) {
	rows, err := q.db.Query(ctx, listImages, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharacterImage
	for rows.Next() {
		var i CharacterImage
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CharacterID,
			&i.FileHash,
			&i.IsMain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMainImage = `-- name: SetMainImage :exec
update character_image set is_main = true where character_id =$1 and id = $2
`

type SetMainImageParams struct {
	CharacterID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) SetMainImage(ctx context.Context, arg SetMainImageParams) error {
	_, err := q.db.Exec(ctx, setMainImage, arg.CharacterID, arg.ID)
	return err
}
