// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const getImage = `-- name: GetImage :one
select id, created_at, owner_id, character_id, file_hash, is_main from character_image where owner_id = $1 and id = $2 limit 1
`

type GetImageParams struct {
	OwnerID uuid.UUID
	ID      uuid.UUID
}

func (q *Queries) GetImage(ctx context.Context, arg GetImageParams) (CharacterImage, error) {
	row := q.db.QueryRow(ctx, getImage, arg.OwnerID, arg.ID)
	var i CharacterImage
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.OwnerID,
		&i.CharacterID,
		&i.FileHash,
		&i.IsMain,
	)
	return i, err
}

const getMainImage = `-- name: GetMainImage :one
select id, created_at, owner_id, character_id, file_hash, is_main from character_image where character_id = $1 and is_main = true limit 1
`

func (q *Queries) GetMainImage(ctx context.Context, characterID uuid.UUID) (CharacterImage, error) {
	row := q.db.QueryRow(ctx, getMainImage, characterID)
	var i CharacterImage
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.OwnerID,
		&i.CharacterID,
		&i.FileHash,
		&i.IsMain,
	)
	return i, err
}

const insertImage = `-- name: InsertImage :one
insert into character_image (owner_id, character_id, file_hash) values ($1, $2, $3) returning id
`

type InsertImageParams struct {
	OwnerID     uuid.UUID
	CharacterID uuid.UUID
	FileHash    string
}

func (q *Queries) InsertImage(ctx context.Context, arg InsertImageParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertImage, arg.OwnerID, arg.CharacterID, arg.FileHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listCharacterImages = `-- name: ListCharacterImages :many
select id, created_at, owner_id, character_id, file_hash, is_main from character_image where owner_id = $1 and character_id = $2
`

type ListCharacterImagesParams struct {
	OwnerID     uuid.UUID
	CharacterID uuid.UUID
}

func (q *Queries) ListCharacterImages(ctx context.Context, arg ListCharacterImagesParams) ([]CharacterImage, error) {
	rows, err := q.db.Query(ctx, listCharacterImages, arg.OwnerID, arg.CharacterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharacterImage
	for rows.Next() {
		var i CharacterImage
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.OwnerID,
			&i.CharacterID,
			&i.FileHash,
			&i.IsMain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
