// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Character struct {
	ID          uuid.UUID
	CreatedAt   pgtype.Timestamp
	OwnerID     uuid.UUID
	Deleted     bool
	Public      bool
	Name        string
	Biography   *string
	Nationality string
	Age         int32
	Body        string
	Breast      string
	Butt        string
	EyesColor   string
	HairStyle   string
	HairColor   string
	MetaParams  string
	MainImageID *uuid.UUID
}

type CharacterImage struct {
	ID          uuid.UUID
	CreatedAt   pgtype.Timestamp
	CharacterID uuid.UUID
	FileHash    string
	IsMain      bool
}

type Glossary struct {
	ID    uuid.UUID
	Type  string
	Value string
}

type GlossaryLocalization struct {
	ID         uuid.UUID
	GlossaryID uuid.UUID
	Local      string
	Name       string
}
