// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    status, 
    positive, 
    negative, 
    seed,
    character_id,
    user_id
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id
`

type CreateTaskParams struct {
	Status      string
	Positive    string
	Negative    string
	Seed        int32
	CharacterID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.Status,
		arg.Positive,
		arg.Negative,
		arg.Seed,
		arg.CharacterID,
		arg.UserID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getTask = `-- name: GetTask :one
SELECT id, created_at, status, user_id, character_id, positive, negative, seed FROM tasks
WHERE id = $1 limit 1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Status,
		&i.UserID,
		&i.CharacterID,
		&i.Positive,
		&i.Negative,
		&i.Seed,
	)
	return i, err
}

const getTaskWithStatus = `-- name: GetTaskWithStatus :one
SELECT id, created_at, status, user_id, character_id, positive, negative, seed FROM tasks
WHERE status = $1 limit 1
`

func (q *Queries) GetTaskWithStatus(ctx context.Context, status string) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskWithStatus, status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Status,
		&i.UserID,
		&i.CharacterID,
		&i.Positive,
		&i.Negative,
		&i.Seed,
	)
	return i, err
}

const listTasksWithStatus = `-- name: ListTasksWithStatus :many
SELECT id, created_at, status, user_id, character_id, positive, negative, seed FROM tasks
where status = $1
ORDER BY created_at
`

func (q *Queries) ListTasksWithStatus(ctx context.Context, status string) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksWithStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Status,
			&i.UserID,
			&i.CharacterID,
			&i.Positive,
			&i.Negative,
			&i.Seed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET 
    status = COALESCE($2, status),
    positive = COALESCE($3, positive),
    negative = COALESCE($4, negative),
    seed = COALESCE($5, seed)
WHERE id = $1
RETURNING id, created_at, status, user_id, character_id, positive, negative, seed
`

type UpdateTaskParams struct {
	ID       uuid.UUID
	Status   string
	Positive string
	Negative string
	Seed     int32
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Status,
		arg.Positive,
		arg.Negative,
		arg.Seed,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Status,
		&i.UserID,
		&i.CharacterID,
		&i.Positive,
		&i.Negative,
		&i.Seed,
	)
	return i, err
}
