-- +goose Up
-- +goose StatementBegin

-- Вставка данных в таблицу glossary
INSERT INTO glossary (type, value) VALUES
-- default_positive
('default_positive', 'score_9'),
('default_positive', 'score_8_up'),
('default_positive', 'score_7_up'),
('default_positive', 'source_anime'),
('default_positive', '1girl'),
('default_positive', 'rating_explicit'),

-- default_negative
('default_negative', 'score_4'),
('default_negative', 'score_3'),
('default_negative', 'score_2'),
('default_negative', 'score_1'),
('default_negative', 'watermark'),
('default_negative', 'signature'),
('default_negative', 'source_cartoon'),
('default_negative', 'text'),
('default_negative', '(mutated hands and fingers:1.4)'),
('default_negative', 'low quality'),


-- body_type
('body_type', 'slim'),
('body_type', 'medium'),

-- breast_type
('breast_type', 'flat'),
('breast_type', 'small'),
('breast_type', 'medium'),
('breast_type', 'large'),

-- butt_type
('butt_type', 'skinny'),
('butt_type', 'athletic'),
('butt_type', 'medium'),
('butt_type', 'large'),

-- eyes_color
('eyes_color', 'brown'),
('eyes_color', 'blue'),
('eyes_color', 'hazel'),
('eyes_color', 'gray'),
('eyes_color', 'amber'),
('eyes_color', 'red'),
('eyes_color', 'violet'),

-- hair_color
('hair_color', 'black'),
('hair_color', 'blue'),
('hair_color', 'brown'),
('hair_color', 'blonde'),
('hair_color', 'red'),
('hair_color', 'auburn'),
('hair_color', 'chestnut'),
('hair_color', 'grey'),
('hair_color', 'white'),
('hair_color', 'salt and pepper'),

-- hair_style
('hair_style', 'asymmetrical cut'),
('hair_style', 'blunt cut'),
('hair_style', 'bob cut'),
('hair_style', 'braided bob'),
('hair_style', 'buzz cut'),
('hair_style', 'choppy cut'),
('hair_style', 'curly bob'),
('hair_style', 'curtain bangs'),
('hair_style', 'faux hawk'),
('hair_style', 'feathered cut'),
('hair_style', 'french bob'),
('hair_style', 'layered cut'),
('hair_style', 'long bob'),
('hair_style', 'mohawk'),
('hair_style', 'pixie cut'),
('hair_style', 'shag cut'),
('hair_style', 'side-swept bangs'),
('hair_style', 'textured cut'),
('hair_style', 'undercut'),
('hair_style', 'wavy bob'),
('hair_style', 'faux hawk short pixie'),
('hair_style', 'brave short haircut with shaved sides'),
('hair_style', 'tapered haircut with shaved side'),
('hair_style', 'stacked bob'),
('hair_style', 'lemonade braids'),
('hair_style', 'middle part ponytails'),
('hair_style', 'deep side part'),
('hair_style', 'french braids'),
('hair_style', 'box braids'),
('hair_style', 'two dutch braids'),
('hair_style', 'wavy cut with curtains bangs'),
('hair_style', 'right side shaved'),
('hair_style', 'sweeping pixie'),
('hair_style', 'smooth lob'),
('hair_style', 'long pixie'),
('hair_style', 'sideswept pixie'),
('hair_style', 'italian bob'),
('hair_style', 'shullet'),

-- nationality
('nationality', 'asian'),
('nationality', 'white'),
('nationality', 'latina'),
('nationality', 'arab'),
('nationality', 'indian'),
('nationality', 'japanese'),
('nationality', 'elf'),
('nationality', 'demon'),
('nationality', 'angel'),

-- action
('action', 'looking at viewer'),
('action', 'looking away'),
('action', 'looking up'),
('action', 'looking down'),
('action', 'looking back'),
('action', 'open mouth'),
('action', 'half-closed mouth'),
('action', 'closed mouth'),
('action', 'open eyes'),
('action', 'half-closed eyes'),
('action', 'closed eyes'),
('action', 'wink'),
('action', 'standing'),
('action', 'sitting'),
('action', 'lying'),
('action', 'walking'),
('action', 'running'),
('action', 'adjusting hair'),
('action', 'waving'),
('action', 'hand on hip'),
('action', 'crossed arms'),
('action', 'smile'),
('action', 'sad'),
('action', 'angry'),
('action', 'sleepy'),
('action', 'tired'),
('action', 'expressionless'),

-- clothes
('clothes', 'underwear'),
('clothes', 'clothed'),
('clothes', 'casual'),
('clothes', 'dress'),
('clothes', 'swimsuit'),
('clothes', 'uniform'),
('clothes', 'bikini'),
('clothes', 'one-piece swimsuit'),
('clothes', 'shirt'),
('clothes', 'blouse'),
('clothes', 'sweater'),
('clothes', 'hoodie'),
('clothes', 'jeans'),
('clothes', 'pants'),
('clothes', 'shorts'),
('clothes', 'skirt'),
('clothes', 'vest'),
('clothes', 'coat'),
('clothes', 'trenchoat'),
('clothes', 'jacket'),
('clothes', 'short dress'),
('clothes', 'long dress'),
('clothes', 'off-shoulder'),
('clothes', 'backless'),
('clothes', 'hairbow'),
('clothes', 'hair ribbon'),
('clothes', 'hair tie'),
('clothes', 'hairband'),
('clothes', 'cap'),
('clothes', 'beanie'),
('clothes', 'bucket hat'),
('clothes', 'sun hat'),
('clothes', 'straw hat'),
('clothes', 'rice hat'),
('clothes', 'witch hat'),
('clothes', 'crown'),
('clothes', 'chain necklace'),
('clothes', 'tooth necklace'),
('clothes', 'choker'),
('clothes', 'pendant'),
('clothes', 'bracelet'),
('clothes', 'watch'),
('clothes', 'ring'),
('clothes', 'earring'),
('clothes', 'anklet'),
('clothes', 'belt'),
('clothes', 'scarf'),
('clothes', 'gloves'),
('clothes', 'mittens'),
('clothes', 'socks'),
('clothes', 'stockings'),
('clothes', 'tights'),
('clothes', 'leggings'),
('clothes', 'boots'),
('clothes', 'sneakers'),
('clothes', 'heels'),
('clothes', 'sandals'),
('clothes', 'flip-flops'),
('clothes', 'slippers'),
('clothes', 'loafers'),
('clothes', 'oxfords'),
('clothes', 'brogues'),
('clothes', 'derbies'),
('clothes', 'monk shoes'),
('clothes', 'chelsea boots'),
('clothes', 'combat boots'),
('clothes', 'riding boots'),
('clothes', 'rain boots'),
('clothes', 'wedge heels'),
('clothes', 'platform heels'),
('clothes', 'stilettos'),
('clothes', 'block heels'),
('clothes', 'kitten heels'),
('clothes', 'moccasins'),
('clothes', 'espadrilles'),
('clothes', 'pumps'),
('clothes', 'flats'),
('clothes', 'ballet flats'),
('clothes', 'mary janes'),
('clothes', 'slingbacks'),
('clothes', 'peep-toe'),
('clothes', 'mule sandals'),
('clothes', 'gladiator sandals'),
('clothes', 'thong sandals'),
('clothes', 'slide sandals'),
('clothes', 'espadrille sandals'),
('clothes', 'wedge sandals'),
('clothes', 'platform sandals'),
('clothes', 'ankle boots'),
('clothes', 'knee-high boots'),
('clothes', 'over-the-knee boots'),
('clothes', 'thigh-high boots'),
('clothes', 'wellington boots'),
('clothes', 'chukka boots'),
('clothes', 'desert boots'),
('clothes', 'hiking boots'),
('clothes', 'work boots'),
('clothes', 'snow boots'),
('clothes', 'cowboy boots'),
('clothes', 'biker boots'),
('clothes', 'duck boots'),
('clothes', 'military boots'),
('clothes', 'western boots'),
('clothes', 'ankle strap heels'),
('clothes', 'chunky heels'),
('clothes', 'cone heels'),
('clothes', 'slingback heels'),

-- environment
('environment', 'sunshine from window'),
('environment', 'neon night, city'),
('environment', 'sunset over sea'),
('environment', 'golden time'),
('environment', 'sci-fi RGB glowing, cyberpunk'),
('environment', 'natural lighting'),
('environment', 'warm atmosphere, at home, bedroom'),
('environment', 'magic lit'),
('environment', 'evil, gothic, in a cave'),
('environment', 'light and shadow'),
('environment', 'shadow from window'),
('environment', 'soft studio lighting'),
('environment', 'home atmosphere, cozy bedroom illumination'),
('environment', 'neon, Wong Kar-wai, warm'),
('environment', 'moonlight through curtains'),
('environment', 'stormy sky lighting'),
('environment', 'foggy forest at dawn'),
('environment', 'golden hour in a meadow'),
('environment', 'rainbow reflections, neon'),
('environment', 'cozy candlelight'),
('environment', 'apocalyptic, smoky atmosphere'),
('environment', 'red glow, emergency lights'),
('environment', 'mystical glow, enchanted forest'),
('environment', 'campfire light'),
('environment', 'harsh, industrial lighting'),
('environment', 'sunrise in the mountains'),
('environment', 'evening glow in the desert'),
('environment', 'moonlight in a dark alley'),
('environment', 'golden glow at a fairground'),
('environment', 'midnight in the forest'),
('environment', 'purple and pink hues at twilight'),
('environment', 'foggy morning, muted light'),
('environment', 'candle-lit room, rustic vibe'),
('environment', 'fluorescent office lighting'),
('environment', 'lightning flash in storm'),
('environment', 'night, cozy warm light from fireplace'),
('environment', 'ethereal glow, magical forest'),
('environment', 'dusky evening on a beach'),
('environment', 'afternoon light filtering through trees'),
('environment', 'blue neon light, urban street'),
('environment', 'red and blue police lights in rain'),
('environment', 'aurora borealis glow, arctic landscape'),
('environment', 'sunrise through foggy mountains'),
('environment', 'golden hour on a city skyline'),
('environment', 'mysterious twilight, heavy mist'),
('environment', 'early morning rays, forest clearing'),
('environment', 'colorful lantern light at festival'),
('environment', 'soft glow through stained glass'),
('environment', 'harsh spotlight in dark room'),
('environment', 'mellow evening glow on a lake'),
('environment', 'crystal reflections in a cave'),
('environment', 'vibrant autumn lighting in a forest'),
('environment', 'gentle snowfall at dusk'),
('environment', 'hazy light of a winter morning'),
('environment', 'soft, diffused foggy glow'),
('environment', 'underwater luminescence'),
('environment', 'rain-soaked reflections in city lights'),
('environment', 'golden sunlight streaming through trees'),
('environment', 'fireflies lighting up a summer night'),
('environment', 'glowing embers from a forge'),
('environment', 'dim candlelight in a gothic castle'),
('environment', 'midnight sky with bright starlight'),
('environment', 'warm sunset in a rural village'),
('environment', 'flickering light in a haunted house'),
('environment', 'desert sunset with mirage-like glow'),
('environment', 'golden beams piercing through storm clouds'),

-- background
('background', 'a cozy bed and a lamp'),
('background', 'a forest clearing with mist'),
('background', 'a bustling marketplace'),
('background', 'a quiet beach at dusk'),
('background', 'an old, cobblestone street'),
('background', 'a futuristic cityscape'),
('background', 'a tranquil lake with mountains'),
('background', 'a mysterious cave entrance'),
('background', 'bookshelves and plants in the background'),
('background', 'an ancient temple in ruins'),
('background', 'tall skyscrapers and neon signs'),
('background', 'a starry sky over a desert'),
('background', 'a bustling café'),
('background', 'rolling hills and farmland'),
('background', 'a modern living room with a fireplace'),
('background', 'an abandoned warehouse'),
('background', 'a picturesque mountain range'),
('background', 'a starry night sky'),
('background', 'the interior of a futuristic spaceship'),
('background', 'the cluttered workshop of an inventor'),
('background', 'the glowing embers of a bonfire'),
('background', 'a misty lake surrounded by trees'),
('background', 'an ornate palace hall'),
('background', 'a busy street market'),
('background', 'a vast desert landscape'),
('background', 'a peaceful library corner'),
('background', 'bustling train station'),
('background', 'a mystical, enchanted forest'),
('background', 'an underwater reef with colorful fish'),
('background', 'a quiet rural village'),
('background', 'a sandy beach with palm trees'),
('background', 'a vibrant coral reef, teeming with life'),
('background', 'snow-capped mountains in distance'),
('background', 'a stormy ocean, waves crashing'),
('background', 'a rustic barn in open fields'),
('background', 'a futuristic lab with glowing screens'),
('background', 'a dark, abandoned castle'),
('background', 'the ruins of an ancient civilization'),
('background', 'a bustling urban street in rain'),
('background', 'an elegant grand ballroom'),
('background', 'a sprawling field of wildflowers'),
('background', 'a dense jungle with sunlight filtering through'),
('background', 'a dimly lit, vintage bar'),
('background', 'an ice cave with sparkling crystals'),
('background', 'a serene riverbank at sunset'),
('background', 'a narrow alley with graffiti walls'),
('background', 'a peaceful zen garden with koi pond'),
('background', 'a high-tech control room'),
('background', 'a quiet mountain village at dawn'),
('background', 'a lighthouse on a rocky coast'),
('background', 'a rainy street with flickering lights'),
('background', 'a frozen lake with ice formations'),
('background', 'an abandoned theme park'),
('background', 'a small fishing village on a pier'),
('background', 'rolling sand dunes in a desert'),
('background', 'a dense forest with towering redwoods'),
('background', 'a snowy cabin in the mountains'),
('background', 'a mystical cave with bioluminescent plants'),
('background', 'a castle courtyard under moonlight'),
('background', 'a bustling open-air night market'),
('background', 'an old train station with steam'),
('background', 'a tranquil waterfall surrounded by trees'),
('background', 'a vineyard in the countryside'),
('background', 'a quaint medieval village'),
('background', 'a bustling harbor with boats'),
('background', 'a high-tech futuristic mall'),
('background', 'a lush tropical rainforest'),

-- nsfw
('nsfw', 'nude'),
('nsfw', 'breast'),
('nsfw', 'clothes lift'),
('nsfw', 'pussy juice trail'),
('nsfw', 'pussy juice puddle'),
('nsfw', 'cum on body'),
('nsfw', 'cum inside'),
('nsfw', 'fingering'),
('nsfw', 'doggystyle'),
('nsfw', 'cowgirl'),
('nsfw', 'reversed cowgirl');
-- +goose StatementEnd


-- +goose Down
-- +goose StatementBegin
-- Удаление данных в обратном порядке (сначала локализации, затем глоссарий)
DELETE FROM glossary_localization;
DELETE FROM glossary;
-- +goose StatementEnd